version: "3.9"

services:
  db:
    image: postgres:13
    container_name: fit-db
    restart: always
    environment:
      POSTGRES_USER: fituser
      POSTGRES_PASSWORD: fitpass
      POSTGRES_DB: fitdb
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fit-monolith
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://fituser:fitpass@db:5432/fitdb
    ports:
      - "5001:5001"

  coach:
    build:
      context: ./coach
      dockerfile: Dockerfile
    container_name: fit-coach
    depends_on:
      - app
    ports:
      - "8000:8000"
